name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "db_newsnow"
database_id = "1314b24d-4112-45ed-ac12-5ee3e9133182"
